version: "3"

services:
  app-service:
    build: ./server
    volumes: 
      - ./server:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://nginx-service:${MINIO_PORT}
      SELF_HOSTED: 1 
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      LOGO_URL: ${LOGO_URL}
      PORT: ${APP_PORT}
    depends_on:
      - nginx-service
      - minio-service
      - couch-init

  minio-service:
    image: minio/minio:RELEASE.2020-12-10T01-54-29Z
    volumes:
      - data1:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx-service:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.template:/etc/nginx/nginx.template:ro
    ports:
      - "${MINIO_PORT}:5001"
    depends_on:
      - minio-service
    command: ["sh", "-c", "envsubst < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]

  couchdb-service:
    image: apache/couchdb:3.0
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    ports:
      - "${COUCH_DB_PORT}:5984"
      - "4369:4369"
      - "9100:9100"
    volumes:
      - couchdb_data:/couchdb

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

volumes:
  couchdb_data:
    driver: local
  data1:
