name: Budibase Release

on: 
 # Trigger the workflow on push,
 # but only for the release branch
 push:
  branches:
    - master
  tags:
    - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x]
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn 
      # - run: yarn lint 
      - run: yarn bootstrap 
      - run: yarn build 
      # - run: yarn test

      - name: Prepare for app notarization (macOS)
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8


      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: packages/server

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
            # macOS notarization API key
            API_KEY_ID: ${{ secrets.api_key_id }}
            API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
